version: '3.8'

services:
  log-analyzer:
    build: .
    container_name: log-analyzer
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python analyzer.py demo
